### ISSUE TITLE
Node.JS wrapper update

### ISSUE THREAD

**Issue by cabbiepete** [mailchimp/APIv3-examples#15]
Just wondering if there are plans or not to update the mailchimp-api module for v3 of the API.

**Comment by toomuchpete** [comment]
Hey @cabbiepete, we do plan to update the wrappers, although Node.js may take a bit longer than the others. We don't have many experienced Node folks on staff and there have been a lot of complaints about the quality of the v2.0 wrapper. We want to make sure that any wrappers we produce for v3.0 are high quality. Since standard HTTP libraries work well for RESTful APIs, getting the wrappers right is more important than getting them out fast.

That said, this repo is for examples, not wrappers, so I'm going to go ahead and close this issue out.

**Comment by cabbiepete** [comment]
Thanks, if the repo for the node mail chimp-api was public I would have posted this there but its not. 

I'd also have started on a fork and pull request to support 3.0. 

No real gripes obviously up to you how you run things. Just FYI community members are happy to contribute if you make it easy my alternative at this stage would be to write my own for the project I am integrating and publish as a separate npm package which seems kinda wasteful.

I'll likely use the 2.0 wrapper provided unless the quality of it is an issue. So far so good from what I've seen its not bad quality. 

My guess at least some of the complaints are potentially more about 2.0 API design being RPC vs RESTful which given you published a wrapper is not a biggie for me.

Thanks for the response anyways, and let me know if you do open up the package again and if I have time I'll contribute.

**Comment by corbanb** [comment]
@toomuchpete would your team be open to making the repo for node.js public and taking contributors?

**Comment by toomuchpete** [comment]
@corbanb I'm not sure about that. In theory it sounds like a really great idea. The details make it more difficult.

The difference between an independent contributor having their own library (like [gibbon](https://github.com/amro/gibbon)) and a library owned by MailChimp is primarily in the amount of support we have to give the project. If we own the repo, we need to spend support hours supporting the library and engineering hours ensuring that the code is solid. Two things we don't really need to do in the case of a library run by another person or group.

If we were in a place where that were our top priority, we would probably also be able to build (or start building) that wrapper library on our own.

What we have found, though, is that well-done 3rd party libraries tend to float to the top. The Gibbon gem, for example, is almost as well used as our own Ruby Gem. 

That said, I'll pass this feedback along to our API team.

**Comment by corbanb** [comment]
@toomuchpete sounds good. Thanks for the heads up.
