### ISSUE TITLE
PHP/WP Example for post to /lists/[id]/members/

### ISSUE THREAD

**Issue by JohannesBeranek** [mailchimp/APIv3-examples#2]
Seems like mailchimp ignores sent ip_signup and timestamp_signup

For basic PHP i would suggest using file_get_contents with stream_context_create, and for Wordpress I would suggest using wp_remote_post.

VERY Basic (working, except for ip_signup and timestamp_signup) WP Code example:

```
$apiKey = trim(get_option('mailchimp_api_key'));
$listID = trim($_POST['id']);
$email = trim($_POST['email']);

$data = array(
    'email_address' => $email,
    'status' => 'subscribed',
    'ip_signup' => $_SERVER['REMOTE_ADDR'],
    'timestamp_signup' => $_SERVER['REQUEST_TIME'],
);

$body = json_encode($data);

$opts = array(
    'headers' => array(
        'Content-Type' => 'application/json',
        'Authorization' => 'apikey ' . $apiKey
    ),
    'body' => $body
);

$apiKeyParts = explode('-', $apiKey);
$shard = $apiKeyParts[1];

$url = 'https://' . $shard . '.api.mailchimp.com/3.0/lists/' . $listID . '/members/';

$response = wp_remote_post( $url, $opts );

if ( is_wp_error( $response ) ) {
    $result = $response->get_error_message();
} else {
    // DEBUG
    $result = print_r($response, true);
}

return $result;
```

**Comment by toomuchpete** [comment]
Hi @griffin1987 -- while we certainly do appreciate the extra code, this would be best submitted in the form of a pull request. I will say that relying on WordPress is probably not ideal, but might be worth its own examples. We'll have PHP examples soon (no WP Requirement), but in the mean time I'd look into [PHP Requests](https://github.com/rmccue/Requests) and [Guzzle](http://guzzle.readthedocs.org/en/latest/).

**Comment by trewknowledge** [comment]
@griffin1987 thanks for this example, I am finding it very useful. Do you know how I can use "PATCH" in the above example to update existing members?

**Comment by toomuchpete** [comment]
@trewknowledge The docs for [wp_remote_post()](https://codex.wordpress.org/Function_Reference/wp_remote_post) will be of use. You can pass the non-POST method as an argument to the function

**Comment by trewknowledge** [comment]
Thanks @toomuchpete. When I change the method to PATCH like this...

```
$opts = array(
                                'headers' => array(
                                    'Content-Type' => 'application/json',
                                    'Authorization' => 'apikey ' . $apiKey,
                                ),
                                'body' => $body,
                                'method' => 'PATCH',
                            );

```

I get the following error: 

["body"]=> string(289) "{"type":"http://kb.mailchimp.com/api/error-docs/405-method-not-allowed","title":"Method Not Allowed","status":405,"detail":"The requested method and resource are not compatible. See the Allow header for this resource's available methods.","instance":"9ebeb865-5a55-42cb-ab74-512aa6768e67"}" ["response"]=> array(2) { ["code"]=> int(405) ["message"]=> string(18) "Method Not Allowed" } 

Is this more an issue with the wp_remote_post() function or an issue with the API?

**Comment by toomuchpete** [comment]
It's difficult to tell without knowing what endpoint you're hitting and what actual body you're sending, but the answer (most likely) is that the issue is neither with the API nor with the wp_remote_post() method. The issue, probably, is that wp_remote_post() is doing exactly what it's told, but it's not being told the right things . . . your best bet is to contact API support [apihelp at mailchimp dot com] or fall back to an older version of the API until there are wrapper libraries available for v3.0.

**Comment by trewknowledge** [comment]
The issue was on my end. I needed to be using this endpoint "/lists/{list_id}/members/{id}"

The tricky part now is that I am trying to use this when a user subscribes (or updates their status) by filling out a form, and there is no way of knowing what their ID is, just their email address.

Is there an alternate way of doing this using v3.0?

**Comment by toomuchpete** [comment]
Hi @trewknowledge! It's not really practical for us to provide API support in github issues like this. Please get in touch with our dedicated support team as mentioned above. Thanks!

**Comment by trewknowledge** [comment]
Thanks @toomuchpete, will do!

**Comment by beljems** [comment]
visit this page https://developer.mailchimp.com/documentation/mailchimp/reference/lists/members/#edit-put_lists_list_id_members_subscriber_hash
