### ISSUE TITLE
How to get interest id used in conditions for creating segments?

### ISSUE THREAD

**Issue by ivanacorovic** [mailchimp/APIv3-examples#20]
Hello,

this is not really an issue, I just need to create segment related to a group (interest), and I don't know where the interest id comes from, since it's not the hex id I'm used to, but rather a 5-digit-integer. Are they even related? Help me out here?

**Comment by toomuchpete** [comment]
Hi, @ivanacorovic -- we can't offer API support via Github Issues on this repo. Please reach out to apihelp@mailchimp.com and we can take care of you there. Thanks!
