### ISSUE TITLE
ID is not matching MD5 email

### ISSUE THREAD

**Issue by mattlo** [mailchimp/APIv3-examples#22]
How is this possible?
![screen shot 2015-11-18 at 11 06 29 pm](https://cloud.githubusercontent.com/assets/1714244/11262860/d05e3bf4-8e49-11e5-8d80-99bddc16b544.png)

That email should be `a830235287c51f9e17500e98352d0a95`

**Comment by toomuchpete** [comment]
Hi, @mattlo. This is not a place where we can offer API support. Please reach out to our API Help team if you need assistance.
