### ISSUE TITLE
Subscribes to MailChimp API v3 fail with 500 error in specific cases (malformatted email, blacklisted domain,...)

### ISSUE THREAD

**Issue by bsjut** [mailchimp/APIv3-examples#28]
We see an issue with the PUT method on the /members endpoint that generates 500 errors: This was already supported to the API support team, but I'm going to document it here, as well, as other developers are likely to run into the same situation. 

When using the PUT method to add or update a member, the following cases will lead to a 500 error from the MailChimp API: 
- the email address contains a comma
- the email contains a "." at the end
- the email address is on a domain that has been blacklisted by MailChimp (e.g. googlegroups.com)

The error response is in all cases: 
{
  "type": "about:blank",
  "title": "Internal Server Error",
  "status": 500,
  "detail": "A deep, internal error has occurred during the processing of your request. Please contact support.",
  "exception": "EXCEPTIONID",
  "instance": "INSTANCEID"
}

We assume that MailChimp is putting all emails through a validation check, but the result of the validation check is not properly supported in the API v3, so we get a 500 back. This is really bad, as we can of course check for commas and "."s in malformatted emails, but the blacklisted domains are not public and we can't check. A 500 response is the wrong answer to it and we need a proper error code to do the appropriate error handling on our side.

How can the error be reproduced? here are the example payloads of these cases:

**Example payload ("," in email address)** 
{
    "email_address": "firstname.lastname@maildomain,com",
    "status_if_new": "subscribed",
    "merge_fields": {
        "FNAME": "Bjoern",
        "LNAME": "Sjut"
    }
}

**Example payload ("." in email address)** 
{
    "email_address": "firstname.lastname@maildomain.com.",
    "status_if_new": "subscribed",
    "merge_fields": {
        "FNAME": "Bjoern",
        "LNAME": "Sjut"
    }
}

**Example payload (blacklisted domain)** 
{
    "email_address": "firstname.lastname@googlegroups.com",
    "status_if_new": "subscribed",
    "merge_fields": {
        "FNAME": "Bjoern",
        "LNAME": "Sjut"
    }
}

**Comment by bsjut** [comment]
Please note that this bug is likely to affect all MailChimp extensions that are used to sync data across systems (i.e. ecommerce extensions) and the put method is used on the new API. Whenever one customer would have a blacklisted/malformatted email domain this might seriously hamper the sync, if a 500 error is assumed to be temporary.

**Comment by toomuchpete** [comment]
Hi @bsjut -- this appears to be a bug report for the MailChimp API. We cannot do support for the API via this repository. You should reach out to MailChimp customer support: apihelp@mailchimp.com.
