### ISSUE TITLE
API v3 Python Client?

### ISSUE THREAD

**Issue by ye** [mailchimp/APIv3-examples#29]
We've been comfortably using API v2 via an official Python client (https://pypi.python.org/pypi/mailchimp) for the past year or so. 

However, I haven't yet to found any equivalent API v3 python client library or seeing any signs of [the official python client lib](https://bitbucket.org/mailchimp/mailchimp-api-python) adopting the support for API v3. And in this repo's API v3 Python code examples, there's quite a bit of boilerplate code to deal with API v3's REST API via Requests and JSON.

Is mailchimp working on either to improve upon the existing Python client lib for v2 or building a new python client for v3 or Python client is simply not coming back after you sunset API v2?

Would love to hear the roadmap for that, thanks!

**Comment by toomuchpete** [comment]
Hi @ye. This repository is for API v3 examples. We can't offer support for the MailChimp API or other wrapper libraries here. If you have questions, please reach out to apihelp@mailchimp.com.

**Comment by ye** [comment]
@toomuchpete I understand this is for API v3 examples and I am not asking for support for MailChimp API. I am simply asking for the intent for the continuity of MailChimp API python client lib in the new v3 era since v2 is going to be sunset by the end of 2016 or so as told: http://devs.mailchimp.com/blog/sunsetting-previous-mailchimp-api-versions/

The official MailChimp bitbucket repo https://bitbucket.org/mailchimp/mailchimp-api-python/ doesn't even have the issues feature to allow me to ask that question.

This is sort of related because apparently coding against MailChimp API v3 has to resort to `requests` and `json` directly with the REST API endpoints seems to be [a terrible way](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) to interact with MailChimp API. One alternative is to write a wrapper on our own but I am curious to know the roadmap so that I don't waste time creating our own.

If you know the simple answer, would love to hear it. Thanks.

**Comment by toomuchpete** [comment]
Hi @ye. Unfortunately, we simply can't offer API support by way of this repository. If you have questions, you should reach out to apihelp@mailchimp.com. 

FWIW: our internal usage of MailChimp API v3 does not rely on a generic client library. Rather, we start with basic REST interaction and then abstract patterns that are meaningful in the context of the application we're building. A client library doesn't do much to reduce duplicated code, it just changes what the duplication looks like (and introduces an external dependency in the process).

**Comment by ye** [comment]
Pete, to be fair, I wouldn't consider a simple yes or no answer to be "support". It's fine if you don't have the answer (I thought you'd know since you are part of the team[0]). But the below statement is simply **untrue**.

> A client library doesn't do much to reduce duplicated code, it just changes what the duplication looks like (and introduces an external dependency in the process).

The existing MailChimp API v2 python client [1] has been doing exactly it, that is, making language specific client libraries to wrap around REST API and convert responses to appropriate language-specific objects so that it helps speed up development and reduce boilerplate code to deal with HTTP communication / JSON encoding/decoding. In fact, language-specific client library wrapper for REST API apparently is a norm. [2][3][4][5][6]

[0] https://bitbucket.org/mailchimp/profile/members
[1] https://bitbucket.org/mailchimp/mailchimp-api-python
[2] https://github.com/sailthru/sailthru-python-client
[3] https://bitbucket.org/mailchimp/mandrill-api-python/
[4] https://stripe.com/docs/libraries
[5] https://github.com/braintree/braintree_python
[6] https://github.com/sendgrid/sendgrid-python

**Comment by toomuchpete** [comment]
Hi @ye. We can certainly agree to disagree on that point. I've seen how replacing that exact library you're talking about can result in a reduction in TLOC without a dedicated client library. 

Still, the questions you're asking are best directed at our customer support team.
