### ISSUE TITLE
python wrapper for APIv3.0?

### ISSUE THREAD

**Issue by sxbo672158** [mailchimp/APIv3-examples#3]
Will there be a new python wrapper for apiv3.0 like you had for [v2.0](https://bitbucket.org/mailchimp/mailchimp-api-python/overview)?

**Comment by toomuchpete** [comment]
Yes, but we don't currently have an ETA. In the mean time, a few minutes in the API Playground and a general-purpose HTTP library like Requests should get you moving.

**Comment by ktmatzdorf** [comment]
Von meinem iPhone gesendet
