### ISSUE TITLE
Can I get my account's all mailchimp campaign's details hitting the api only one time instead of hitting the api for each of the campaign ? if yes, how ? only using mailchimp api v3.0 

### ISSUE THREAD

**Issue by jeetm** [mailchimp/APIv3-examples#30]
Can I get my account's all mailchimp campaign's details hitting the api only one time instead of hitting the api for each of the campaign ? if yes, how ? only using mailchimp api v3.0

**Comment by toomuchpete** [comment]
Hi @jeetm, this sounds like a question for our customer support team! You can reach them at apihelp @ mailchimp.com

**Comment by jeetm** [comment]
ok , thanks
