### ISSUE TITLE
InsecureRequestWarning and placing the api key

### ISSUE THREAD

**Issue by mariuswallin** [mailchimp/APIv3-examples#31]
Hi. Thanks for this one.

I wonder about the InsecureRequestWarning due to HTTPS. Is it ok to suppress that?

And i wonder if I could add the api key directly response = requests.get(endpoint, auth=('apikey', config.apikey), verify=False) in a function? (security)

I am using Django and are rendering the respons in a template.

**Comment by toomuchpete** [comment]
Hi, @wallinmedia -- this looks like a support request. Unfortunately, we cannot offer API support through this repo. You'll want to reach out to apihelp@mailchimp.com for assistance.
