### ISSUE TITLE
Create list doesn't work

### ISSUE THREAD

**Issue by Shetza** [mailchimp/APIv3-examples#5]
Hi !
Thanks in advance for your answer and the job you did so far ;)

I try, from your 'lists.py' to make a "createList.py' (code bellow) but I always receive the same 400 bad request from mailchimp api. Would you take a look on my code please ?

---

Code:

from config import MailChimpConfig
import requests, json

config = MailChimpConfig()

endpoint = config.api_root + "/lists"
headers  = {'Authorization': 'apikey ' + config.apikey}

params   = {
    'name': 'List API python',
    'permission_reminder': 'This is an API test',
    'email_type_option': False,
    'contact': {
        'company': 'My Company',
        'address1': '',
        'city': 'Paris',
        'state': '',
        'zip': '75000',
        'country': '54'
    },
    'campaign_defaults': {
        'from_name': 'Shetza',
        'from_email': 'test@test.com',
        'subject': 'Test from API',
        'language': 'fr'
    }
}

response = requests.post(endpoint, headers=headers, params=params)
body     = response.json()

if (response.status_code != 200):
    print "Error: {} {}".format(str(response.status_code), response.reason)
    print json.dumps(body, indent=4)
else:
    print 'ok'

---

Response:

Error: 400 Bad Request
{
    "status": 400, 
    "errors": [
        {
            "field": "", 
            "message": "Schema describes object, NULL found instead"
        }
    ], 
    "title": "Invalid Resource", 
    "detail": "The resource submitted could not be validated. For field-specific details, see the 'errors' array.", 
    "instance": "74583a62-11e0-403e-9c4a-d53a61439933", 
    "type": "http://kb.mailchimp.com/api/error-docs/400-invalid-resource"
}

**Comment by toomuchpete** [comment]
Hi @Shetza -- I haven't tried to run the code, but the issue appears to be that you're not passing a POST body. With the requests library, the 'params' parameter refers to the Querystring. You'll need to JSON Encode your list data and pass it into the `post` method via a `data` parameter. 

Here's an example:

``` python
import requests, json, random
from pprint import pprint
from config import apiv3_root as api_root, dev_api_key as api_key

payload = {
    'name': "Freddie's Joke List",
    'campaign_defaults': {
        "subject": "Sample Subject",
        "language": "EN-US",
        'from_email': 'pete.holiday@freddiesjokes.com',
        'from_name':  'Pete Holiday'
    },
    'contact': {
        'company': "Company Name",
        'address1': '123 Banana Lane',
        'city': 'Atlanta',
        'state': 'GA',
        'zip': '30308',
        'country': 'US'
    },
    'permission_reminder': "You gave me permission to send you jokes on my website!",
    "email_type_option": False
}

response = requests.post("{root}/lists/".format(root=api_root), auth=('apikey', api_key), data=json.dumps(payload))

print ' '.join(['Response code:', str(response.status_code)])
print "Headers:"
for header in response.headers:
    print '\t'.join(['',header.ljust(20), response.headers[header]])

print "\nRaw Response:"
print response.text

print "\nJSON:"
print json.dumps(response.json(), indent=4, sort_keys=True)
```

**Comment by toomuchpete** [comment]
I'll get a list creation example up to help clarify!

**Comment by Shetza** [comment]
Thansk @toomuchpete ! It's working very well like that ;)
