### ISSUE TITLE
Automated- Cart abandoned emails in queue but not sending?

### ISSUE THREAD

**Issue by BrandynL** [mailchimp/APIv3-examples#50]
I see users in queue for these automation, but the emails aren't actually sending.
Is there a log somewhere or anything else perhaps to assist with troubleshooting?

Here's the data i'm sending using PHP/Curl:
`$data = [
            'id' => $email,
            'customer' => array(
                'id' => $email,
                'email_address' => $email,
                'opt_in_status' => true,
            ),
            'currency_code' => 'USD',
            'order_total' => 80,
            'lines' => array(
                array(
                        'id' => 'cleaning',
                        'product_id' => 'cleaning',
                        'product_variant_id' => 'cleaning',
                        'quantity' => 1,
                        'price' => 80,
                    )
            ),
        ];`

$email is set and valid, and the items inside my lines array are valid as well, and stored within my connected store - Is there missing data required?

Making a GET to my /store/carts returns the appropriate carts, but the emails wont send for whatever reason... any insights?

**Comment by gonzaloebiz** [comment]
Hi @BrandynL 

the abandoned cart automation does not work until the associated store is completely synced, [get the store](https://developer.mailchimp.com/documentation/mailchimp/reference/ecommerce/stores/#read-get_ecommerce_stores_store_id) and check the is_syncing field

**Comment by BrandynL** [comment]
Hey @gonzaloebiz,
Thanks for your reply. Unfortunately I don't think that is the issue,

I only have one product on my store and it wont ever change, so the value for in_syncing is false when i get the the store id after creating a new cart. I also see that abandoned_cart is_supported is set to true.

Somewhere in between all of this, the endpoint for GET `/3.0/ecommerce/stores/{store_id}/carts` started returning 404 - even when using the API playground. The carts exist because delete works though.
😖😖

**Comment by BrandynL** [comment]
This has been resolved. the [checkout_url is a required cart property](https://developer.mailchimp.com/documentation/mailchimp/reference/ecommerce/stores/carts/) for abandoned carts to trigger, but it is not required to create the cart object on mailchimp. I was missing this property when creating carts.
