### ISSUE TITLE
Possible to add members to list in bulk? 

### ISSUE THREAD

**Issue by chrisjhoughton** [mailchimp/APIv3-examples#6]
Hi guys! I've been using the [list members collection schema](https://us5.api.mailchimp.com/schema/3.0/Lists/Members/Collection.json) to add users to a list - it's all working great. However I was wondering if it's possible to add users in bulk to a list in api v3.0? 

I noticed you've had this capability in previous versions, so thought I'd ask :) - I'd rather not hammer your APIs.

**Comment by toomuchpete** [comment]
Hi @chrisjhoughton -- We don't have batch operations ready yet (see [our roadmap](http://kb.mailchimp.com/api/article/3-roadmap) for other things that aren't quite ready yet), so feel free to hammer away for now!

**Comment by chrisjhoughton** [comment]
Many thanks for clarifying
