### ISSUE TITLE
API Key Missing Error

### ISSUE THREAD

**Issue by nrakochy** [mailchimp/APIv3-examples#8]
I am testing out the new API for subscribing new list member.   

My request: 

```
curl -H "Content-Type: application/json" -d '{"apikey": "myUniqueAPIKeyHere", 
"email": {"email": "sample@example.com"} }' 
https://us9.api.mailchimp.com/3.0/lists/uniquelistid1234/members
```

Response: 

```
{"type":"http://kb.mailchimp.com/api/error-docs/401-api-key-missing",
"title":"API Key Missing","status":401,"detail":"Your request did not include an API key.",
"instance":"uniqueinstance1234"}
```

Can you please advise? This will help sort out what needs to happen in language-specific apps. Many thanks.

**Comment by toomuchpete** [comment]
Hi, @nrakochy!
Unfortunately, we can't offer API support via GitHub issues. If you need help, please email apihelp at mailchimp dot com. That said, it looks like you're sending a v2.0 request to a v3.0 endpoint. Please check out the [getting started guide for v3.0](http://kb.mailchimp.com/api/article/api-3-overview).

**Comment by nrakochy** [comment]
Thanks. For future reference, the code samples for the curl request can be found here: 

```
http://mailchimp.com/api-v3/
```
